import Link from "next/link";
import { ArrowRight, ArrowUpRight, Compass, NotebookPen, Plus, Sprout, UserRound, Users } from "lucide-react";
import { dashboardData } from "@/lib/data";
import { PageHeading } from "@/components/page-heading";
import { ButtonLink } from "@/components/ui/button";
import { StudentCard, OpportunityCard } from "@/components/cards";
import { EmptyState } from "@/components/states";

export const metadata = { title: "Dashboard" };
export default async function Dashboard() {
  const data = await dashboardData();
  return <>
    <PageHeading eyebrow="A LITTLE CONNECTION GOES A LONG WAY" title={`Welcome back, ${data.profile.full_name.split(" ")[0]}`} description="New people, shared interests, and your next big thing."><ButtonLink href="/create-opportunity"><Plus size={16} />Create Opportunity</ButtonLink></PageHeading>
    <section className="mb-8 grid gap-4 sm:grid-cols-3" aria-label="Campus statistics">{[{ label: "Students", value: data.students, note: "People in your campus network", icon: Users, href: "/students", color: "bg-[#efeafa] text-[#8769b6]" }, { label: "Active Opportunities", value: data.opportunities, note: "Ideas looking for the right people", icon: Compass, href: "/opportunities", color: "bg-[#edf2e5] text-[#86975f]" }, { label: "My Posts", value: data.mine, note: "Your open collaboration opportunities", icon: NotebookPen, href: "/my-opportunities", color: "bg-[#fbefdf] text-[#bd935b]" }].map(({ label, value, note, icon: Icon, href, color }) => <Link href={href} key={label} className="panel group flex items-start justify-between gap-4 p-5"><div><p className="mb-2 text-xs text-muted">{label}</p><p className="text-[29px] leading-none font-semibold tracking-tight">{value}</p><p className="mt-3 text-[10px] text-muted">{note}</p></div><span className={`rounded-xl p-2.5 ${color}`}><Icon size={19} strokeWidth={1.5} /></span></Link>)}</section>
    {(!data.profile.bio || !data.profile.skills.length) && <section className="mb-8 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[#e2d8ee] bg-[#f1edf8] p-5"><div className="flex items-center gap-4"><span className="rounded-xl bg-white/75 p-3 text-[#9377b8]"><Sprout size={24} /></span><div><h2 className="text-sm font-semibold tracking-tight">Good connections start with you.</h2><p className="mt-1 text-xs text-[#8e7e9e]">Add your skills and a short bio to help people find you.</p></div></div><ButtonLink href="/profile" variant="secondary">Complete profile<ArrowRight size={15} /></ButtonLink></section>}
    <section className="mb-9"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Fresh opportunities</h2><p className="mt-1 text-xs text-muted">A good idea is even better with the right team.</p></div><Link className="text-link whitespace-nowrap" href="/opportunities">View all<ArrowRight size={14} /></Link></div>{data.recent.length ? <div className="grid gap-5 lg:grid-cols-2">{data.recent.map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</div> : <EmptyState title="No opportunities yet." description="Be the first to put an idea out there. Your next teammate could be waiting." href="/create-opportunity" action="Create an opportunity" />}</section>
    <section className="mb-9"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">People you might click with</h2><p className="mt-1 text-xs text-muted">Recent peers, with shared skills and interests first.</p></div><Link className="text-link whitespace-nowrap" href="/students">Discover all<ArrowRight size={14} /></Link></div>{data.recommended.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{data.recommended.map((student) => <StudentCard student={student} key={student.id} />)}</div> : <EmptyState title="You’re early. That’s a good thing." description="Students will appear here as they join. Make sure your profile is ready to meet them." href="/profile" action="Edit your profile" />}</section>
    <section><h2 className="mb-4 text-sm font-semibold">Make your next move</h2><div className="grid gap-3 sm:grid-cols-3">{[{ label: "Create Opportunity", href: "/create-opportunity", icon: Plus }, { label: "Discover Students", href: "/students", icon: Users }, { label: "Edit Profile", href: "/profile", icon: UserRound }].map(({ label, href, icon: Icon }) => <Link key={href} href={href} className="panel flex items-center gap-3 p-4 text-xs font-medium"><Icon size={17} className="text-primary" />{label}<ArrowUpRight className="ml-auto text-[#aaa0b5]" size={16} /></Link>)}</div></section>
  </>;
}
