import { Suspense } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CalendarDays, Pencil, GraduationCap } from "lucide-react";
import { getOpportunity, requireUser } from "@/lib/data";
import { dateLabel } from "@/lib/utils";
import { Avatar } from "@/components/ui/avatar";
import { ButtonLink } from "@/components/ui/button";
import { CategoryBadge, Tags } from "@/components/cards";
import { DeleteOpportunity } from "@/components/delete-opportunity";
import { SavedToast } from "@/components/forms/feedback";
export const metadata = { title: "Opportunity Details" };
export default async function OpportunityDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params, opportunity = await getOpportunity(id), { user } = await requireUser();
  const own = opportunity.user_id === user.id;
  return <><Suspense><SavedToast /></Suspense><Link href="/opportunities" className="text-link mb-6"><ArrowLeft size={14} />All opportunities</Link><div className="grid items-start gap-6 lg:grid-cols-[1fr_280px]"><article className="panel p-6 sm:p-9"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><CategoryBadge category={opportunity.category} /><span className="flex items-center gap-1.5 text-xs text-muted"><CalendarDays size={14} /><time dateTime={opportunity.created_at}>{dateLabel(opportunity.created_at)}</time></span></div><h1 className="text-[28px] leading-[1.35] font-semibold break-words tracking-[-.035em]">{opportunity.title}</h1><div className="mt-8 border-t border-[#eeebf3] pt-7"><h2 className="mb-4 text-sm font-semibold tracking-tight">The opportunity</h2><p className="text-sm leading-8 whitespace-pre-wrap break-words text-muted">{opportunity.description}</p></div><div className="mt-8 border-t border-[#eeebf3] pt-7"><h2 className="mb-4 text-sm font-semibold tracking-tight">Skills to bring</h2>{opportunity.skills_required.length ? <Tags tags={opportunity.skills_required} limit={12} /> : <p className="text-sm text-muted">No specific skills required. Bring your curiosity.</p>}</div>{own && <div className="mt-8 flex flex-wrap gap-3 border-t border-[#eeebf3] pt-6"><ButtonLink href={`/opportunities/${id}/edit`} variant="secondary"><Pencil size={14} />Edit Opportunity</ButtonLink><DeleteOpportunity id={id} redirectAfter /></div>}</article><aside className="space-y-5"><div className="panel p-6"><p className="eyebrow mb-5 !text-[10px]">MEET THE PERSON BEHIND IT</p><Avatar name={opportunity.author?.full_name ?? "Student"} large /><h2 className="mt-4 text-lg font-semibold">{opportunity.author?.full_name ?? "Campus student"}</h2>{opportunity.author && <p className="mt-2 text-xs leading-6 text-muted"><GraduationCap size={14} className="mr-1 inline" />{opportunity.author.branch}<br />Year {opportunity.author.year}</p>}<p className="mt-4 line-clamp-3 text-xs leading-6 text-muted">{opportunity.author?.bio || "Great collaborations start with getting to know each other."}</p><ButtonLink href={`/students/${opportunity.user_id}`} variant="secondary" className="mt-6 w-full">View Student Profile<ArrowUpRight size={15} /></ButtonLink></div><div className="rounded-xl border border-[#e4e6d6] bg-[#f5f6ed] p-5"><h3 className="text-xs font-semibold tracking-normal text-[#7c805b]">A little context goes a long way.</h3><p className="mt-2 text-xs leading-6 text-[#8a8d71]">Explore their profile and other opportunities to see if your interests align. CampusConnect does not provide messaging.</p></div></aside></div></>;
}
